# Generated by Django 4.1.1 on 2022-10-14 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='done',
            field=models.CharField(choices=[('Doing', 'Doing'), ('Done', 'Done')], max_length=5),
        ),
    ]
